In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2], [3, np.nan]])

In [3]:
a

array([[ 1.,  2.],
       [ 3., nan]])

In [4]:
np.nanmax(a)

3.0

In [5]:
np.nanmax(a, axis=0)

array([3., 2.])

In [6]:
np.nanmax(a, axis=1)

array([2., 3.])

In [7]:
np.nanmax([1, 2, np.nan, np.NINF])

2.0

In [8]:
np.nanmax([1, 2, np.nan, np.inf])

inf